export const LABELS = {
  appName: 'FamInventar',
  dashboard: 'Übersicht',
  collections: 'Sammlungen',
  newItem: 'Neues Teil',
  newCollection: 'Neue Sammlung',
  playLog: 'Spielprotokoll',
  statistics: 'Statistik',
  family: 'Familie',
  settings: 'Einstellungen',
  login: 'Anmelden',
  register: 'Registrieren',
  logout: 'Abmelden',
  save: 'Speichern',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',
  search: 'Suchen...',
  value: 'Wert',
  totalValue: 'Gesamtwert',
  noItems: 'Noch keine Teile vorhanden',
  noCollections: 'Noch keine Sammlungen vorhanden',
  noPlayLogs: 'Noch keine Spielsitzungen erfasst',
  items: 'Teile',
  item: 'Teil',
  collection: 'Sammlung',
  name: 'Name',
  description: 'Beschreibung',
  category: 'Kategorie',
  photo: 'Foto',
  type: 'Typ',
  normal: 'Normal',
  toy: 'Spielzeug',
  parent: 'Elternteil',
  child: 'Kind',
  familyName: 'Familienname',
  memberName: 'Name',
  role: 'Rolle',
  addMember: 'Mitglied hinzufügen',
  topToys: 'Top 5 Lieblingsspielzeuge',
  playSession: 'Spielsitzung',
  logPlay: 'Spiel eintragen',
  duration: 'Dauer (Minuten)',
  notes: 'Notizen',
  allMembers: 'Alle Mitglieder',
  all: 'Alle',
  email: 'E-Mail',
  password: 'Passwort',
  passwordConfirm: 'Passwort bestätigen',
  noAccount: 'Noch kein Konto?',
  hasAccount: 'Bereits ein Konto?',
  welcome: 'Willkommen!',
  setupFamily: 'Familie einrichten',
  step: 'Schritt',
  next: 'Weiter',
  back: 'Zurück',
  finish: 'Fertig',
  totalItems: 'Gesamte Teile',
  totalCollections: 'Sammlungen',
  playHours: 'Spielstunden',
  recentActivity: 'Letzte Aktivitäten',
  valueByCollection: 'Wert pro Sammlung',
  playFrequency: 'Spielhäufigkeit',
  categoryDistribution: 'Kategorieverteilung',
  valueTab: 'Wert',
  playTab: 'Spielen',
  collectionsTab: 'Sammlungen',
  confirmDelete: 'Wirklich löschen?',
  confirmDeleteText: 'Diese Aktion kann nicht rückgängig gemacht werden.',
  owner: 'Besitzer',
  createdAt: 'Erstellt am',
  lastPlayed: 'Zuletzt gespielt',
  playCount: 'Gespielt',
  times: 'Mal',
  euro: '€',
  uploadPhoto: 'Foto hochladen',
  changePhoto: 'Foto ändern',
  removePhoto: 'Foto entfernen',
  loading: 'Laden...',
  error: 'Fehler',
  success: 'Erfolgreich',
}

export const CATEGORIES = [
  { id: 'schuhe', name: 'Schuhe', icon: '👟' },
  { id: 'autos', name: 'Autos', icon: '🚗' },
  { id: 'puzzle', name: 'Puzzle', icon: '🧩' },
  { id: 'puppen', name: 'Puppen', icon: '🧸' },
  { id: 'lego', name: 'LEGO', icon: '🧱' },
  { id: 'buecher', name: 'Bücher', icon: '📚' },
  { id: 'kleidung', name: 'Kleidung', icon: '👗' },
  { id: 'sport', name: 'Sport', icon: '⚽' },
  { id: 'elektronik', name: 'Elektronik', icon: '🎮' },
  { id: 'brettspiele', name: 'Brettspiele', icon: '🎲' },
  { id: 'figuren', name: 'Figuren', icon: '🦸' },
  { id: 'musik', name: 'Musik', icon: '🎵' },
  { id: 'kunst', name: 'Kunst', icon: '🎨' },
  { id: 'sonstiges', name: 'Sonstiges', icon: '📦' },
]

export const COLLECTION_ICONS = [
  '👟', '🚗', '🧩', '🧸', '🧱', '📚', '👗', '⚽', '🎮', '📦',
  '🎨', '🎵', '🌿', '🏠', '💎', '🎁', '🧳', '🔧', '🎲', '🪀',
  '🎸', '🎪', '🦸', '🐻', '🌟', '🚀', '🎯', '🏆', '💡', '🧪',
]

export const AVATARS = [
  '👦', '👧', '👨', '👩', '🧒', '👶',
  '🦊', '🐻', '🐰', '🐱', '🐶', '🦄',
  '🌟', '🌈', '🦋', '🌸', '⚡', '🎈',
]

export const CHART_COLORS = [
  '#FF8A65', '#4DB6AC', '#FFD54F', '#CE93D8', '#81D4FA',
  '#A5D6A7', '#F48FB1', '#FFAB91', '#80CBC4', '#FFF176',
]
