export const LABELS = {
  appName: 'FamInventar',
  dashboard: 'Übersicht',
  collections: 'Inventar',
  newItem: 'Neues Teil',
  newCollection: 'Neue Kategorie',
  playLog: 'Spielprotokoll',
  statistics: 'Statistik',
  settings: 'Einstellungen',
  login: 'Anmelden',
  register: 'Registrieren',
  logout: 'Abmelden',
  save: 'Speichern',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',
  search: 'Suchen...',
  value: 'Wert',
  totalValue: 'Gesamtwert',
  noItems: 'Noch keine Teile vorhanden',
  noCollections: 'Noch keine Kategorien vorhanden',
  noPlayLogs: 'Noch keine Spielsitzungen erfasst',
  items: 'Teile',
  item: 'Teil',
  collection: 'Kategorie',
  name: 'Name',
  description: 'Beschreibung',
  category: 'Kategorie',
  photo: 'Foto',
  type: 'Typ',
  normal: 'Normal',
  toy: 'Spielzeug',
  topToys: 'Top 5 Lieblingsspielzeuge',
  playSession: 'Spielsitzung',
  logPlay: 'Spiel eintragen',
  duration: 'Dauer (Minuten)',
  notes: 'Notizen',
  all: 'Alle',
  email: 'E-Mail',
  password: 'Passwort',
  passwordConfirm: 'Passwort bestätigen',
  noAccount: 'Noch kein Konto?',
  hasAccount: 'Bereits ein Konto?',
  welcome: 'Willkommen!',
  next: 'Weiter',
  back: 'Zurück',
  finish: 'Fertig',
  totalItems: 'Gesamte Teile',
  totalCollections: 'Kategorien',
  playHours: 'Spielstunden',
  recentActivity: 'Letzte Aktivitäten',
  valueByCollection: 'Wert pro Kategorie',
  playFrequency: 'Spielhäufigkeit',
  categoryDistribution: 'Kategorieverteilung',
  valueTab: 'Wert',
  playTab: 'Spielen',
  collectionsTab: 'Kategorien',
  confirmDelete: 'Wirklich löschen?',
  confirmDeleteText: 'Diese Aktion kann nicht rückgängig gemacht werden.',
  owner: 'Besitzer',
  createdAt: 'Erstellt am',
  lastPlayed: 'Zuletzt gespielt',
  playCount: 'Gespielt',
  times: 'Mal',
  euro: '€',
  uploadPhoto: 'Foto hochladen',
  changePhoto: 'Foto ändern',
  removePhoto: 'Foto entfernen',
  loading: 'Laden...',
  error: 'Fehler',
  success: 'Erfolgreich',
  // Extended item fields
  location: 'Standort',
  borrowedTo: 'Ausgeborgt an',
  acquiredType: 'Herkunft',
  bought: 'Gekauft',
  gifted: 'Geschenkt',
  store: 'Geschäft / Laden',
  giftedFrom: 'Geschenkt von',
  occasion: 'Anlass',
  acquiredDate: 'Kaufdatum',
  receipt: 'Rechnung',
  uploadReceipt: 'Rechnung hochladen',
  viewReceipt: 'Rechnung ansehen',
  imageUrl: 'Bild-URL',
  orUrl: 'oder URL einfügen',
  moreDetails: 'Weitere Details',
  hideDetails: 'Details ausblenden',
  noOccasion: 'Kein bestimmter Anlass',
  acquiredInfo: 'Herkunft & Kauf',
  photoUrlPlaceholder: 'Bild-URL einfügen...',
  saveUrl: 'URL speichern',
}

export const CATEGORIES = [
  // Kleidung & Accessoires
  { id: 'schuhe', name: 'Schuhe', icon: '👟' },
  { id: 'jacken', name: 'Jacken & Mäntel', icon: '🧥' },
  { id: 'kleidung', name: 'Kleidung', icon: '👗' },
  { id: 'schmuck', name: 'Schmuck & Uhren', icon: '💍' },
  { id: 'taschen', name: 'Taschen & Koffer', icon: '👜' },

  // Elektronik & Medien
  { id: 'elektronik', name: 'Elektronik', icon: '📱' },
  { id: 'konsolen', name: 'Spielkonsolen', icon: '🎮' },
  { id: 'ps5', name: 'PS5 Spiele', icon: '🕹️' },
  { id: 'ps4', name: 'PS4 Spiele', icon: '🎮' },
  { id: 'xbox', name: 'Xbox Spiele', icon: '🟢' },
  { id: 'nintendo', name: 'Nintendo Spiele', icon: '🔴' },
  { id: 'pc_spiele', name: 'PC Spiele', icon: '🖥️' },
  { id: 'videospiele', name: 'Videospiele (allg.)', icon: '👾' },
  { id: 'cd', name: 'CDs', icon: '💿' },
  { id: 'dvd', name: 'DVDs & Blu-ray', icon: '📀' },
  { id: 'vinyl', name: 'Vinyl / Schallplatten', icon: '🎶' },

  // Spielzeug & Kinder
  { id: 'puppen', name: 'Puppen & Stofftiere', icon: '🧸' },
  { id: 'lego', name: 'LEGO & Bausteine', icon: '🧱' },
  { id: 'puzzle', name: 'Puzzle', icon: '🧩' },
  { id: 'brettspiele', name: 'Brettspiele', icon: '🎲' },
  { id: 'autos', name: 'Spielzeugautos', icon: '🚗' },
  { id: 'figuren', name: 'Figuren & Actionfiguren', icon: '🦸' },

  // Sammlungen & Hobby
  { id: 'muenzen', name: 'Münzen', icon: '🪙' },
  { id: 'karten', name: 'Sammelkarten', icon: '🃏' },
  { id: 'briefmarken', name: 'Briefmarken', icon: '📮' },
  { id: 'comics', name: 'Comics & Manga', icon: '📖' },
  { id: 'buecher', name: 'Bücher', icon: '📚' },
  { id: 'kunst', name: 'Kunst & Deko', icon: '🎨' },
  { id: 'musik_instr', name: 'Musikinstrumente', icon: '🎸' },

  // Haus & Garten
  { id: 'moebel', name: 'Möbel', icon: '🛋️' },
  { id: 'kueche', name: 'Küche & Haushalt', icon: '🍳' },
  { id: 'werkzeug', name: 'Werkzeug', icon: '🔧' },
  { id: 'garten', name: 'Garten', icon: '🌿' },

  // Sport & Outdoor
  { id: 'sport', name: 'Sport & Fitness', icon: '⚽' },
  { id: 'outdoor', name: 'Outdoor & Camping', icon: '🏕️' },
  { id: 'fahrrad', name: 'Fahrrad & Zubehör', icon: '🚲' },

  // Fahrzeuge
  { id: 'auto', name: 'Auto & Zubehör', icon: '🚙' },

  // Sonstiges
  { id: 'sonstiges', name: 'Sonstiges', icon: '📦' },
]

export const LOCATIONS = [
  { id: 'zuhause', name: 'Zuhause', icon: '🏠' },
  { id: 'keller', name: 'Keller', icon: '📦' },
  { id: 'dachboden', name: 'Dachboden', icon: '🏚️' },
  { id: 'garage', name: 'Garage', icon: '🚗' },
  { id: 'buero', name: 'Büro / Arbeit', icon: '🏢' },
  { id: 'lager', name: 'Lagerraum', icon: '🏗️' },
  { id: 'ausgeborgt', name: 'Ausgeborgt', icon: '🔄' },
]

export const OCCASIONS = [
  { id: 'geburtstag', name: 'Geburtstag', icon: '🎂' },
  { id: 'weihnachten', name: 'Weihnachten', icon: '🎄' },
  { id: 'ramadan', name: 'Ramadan', icon: '🌙' },
  { id: 'eid', name: 'Eid', icon: '🕌' },
  { id: 'ostern', name: 'Ostern', icon: '🐰' },
  { id: 'hochzeit', name: 'Hochzeit', icon: '💒' },
  { id: 'einschulung', name: 'Einschulung', icon: '🎒' },
  { id: 'namenstag', name: 'Namenstag', icon: '📛' },
  { id: 'sonstiges', name: 'Sonstiger Anlass', icon: '🎁' },
]

export const COLLECTION_ICONS = [
  '👟', '🧥', '👗', '💍', '👜', '📱', '🎮', '🕹️', '👾', '💿',
  '📀', '🎶', '🧸', '🧱', '🧩', '🎲', '🚗', '🦸', '🪙', '🃏',
  '📮', '📖', '📚', '🎨', '🎸', '🛋️', '🍳', '🔧', '🌿', '⚽',
  '🏕️', '🚲', '🚙', '📦', '🎁', '💎', '🏆', '🎯', '💡', '🧪',
]

export const AVATARS = [
  '👦', '👧', '👨', '👩', '🧒', '👶',
  '🦊', '🐻', '🐰', '🐱', '🐶', '🦄',
  '🌟', '🌈', '🦋', '🌸', '⚡', '🎈',
]

export const CHART_COLORS = [
  '#FF8A65', '#4DB6AC', '#FFD54F', '#CE93D8', '#81D4FA',
  '#A5D6A7', '#F48FB1', '#FFAB91', '#80CBC4', '#FFF176',
]

// ═══════════════════════════════════════════
// Handel (Trading) Module
// ═══════════════════════════════════════════

export const HANDEL_LABELS = {
  handel: 'Handel',
  handelDashboard: 'Handels-Übersicht',
  produkte: 'Produkte',
  produkt: 'Produkt',
  neuesProdukt: 'Neues Produkt',
  produktName: 'Produktname',
  einheit: 'Einheit',
  mindestbestand: 'Mindestbestand',
  aktiv: 'Aktiv',
  inaktiv: 'Inaktiv',
  keineProdukte: 'Noch keine Produkte angelegt',
  einkauf: 'Einkauf',
  einkäufe: 'Einkäufe',
  neuerEinkauf: 'Neuer Einkauf',
  charge: 'Charge',
  chargenNr: 'Chargen-Nr.',
  menge: 'Menge',
  gesamtpreis: 'Gesamtpreis',
  preisProEinheit: 'Preis / Einheit',
  lieferant: 'Lieferant',
  einkaufsdatum: 'Einkaufsdatum',
  restbestand: 'Restbestand',
  keineEinkäufe: 'Noch keine Einkäufe vorhanden',
  verkauf: 'Verkauf',
  verkäufe: 'Verkäufe',
  neuerVerkauf: 'Neuer Verkauf',
  käufer: 'Käufer / Händler',
  verkaufspreis: 'Verkaufspreis',
  verkaufsdatum: 'Verkaufsdatum',
  keineVerkäufe: 'Noch keine Verkäufe vorhanden',
  gewinn: 'Gewinn',
  marge: 'Marge',
  umsatz: 'Umsatz',
  gewinnProMonat: 'Gewinn / Monat',
  lagerwert: 'Lagerwert',
  lagerbestand: 'Lagerbestand',
  eingekauft: 'Eingekauft',
  im_lager: 'Im Lager',
  teilweise_verkauft: 'Teilweise verkauft',
  ausverkauft: 'Ausverkauft',
  storniert: 'Storniert',
  reklamation: 'Reklamation',
  offen: 'Offen',
  bezahlt: 'Bezahlt',
  geliefert: 'Geliefert',
  abgeschlossen: 'Abgeschlossen',
  niedrigerBestand: 'Niedriger Bestand',
  alteCharge: 'Alte Charge',
  alterWarnung: 'Älter als 6 Monate',
  zumHandel: 'Zum Handel',
  offeneVerkäufe: 'Offene Verkäufe',
  aktiveChargen: 'Aktive Chargen',
}

export const PRODUCT_UNITS = [
  { id: 'kg', name: 'Kilogramm (kg)', short: 'kg' },
  { id: 'g', name: 'Gramm (g)', short: 'g' },
  { id: 'stk', name: 'Stück', short: 'Stk.' },
  { id: 'l', name: 'Liter (L)', short: 'L' },
  { id: 'ml', name: 'Milliliter (ml)', short: 'ml' },
  { id: 'pkg', name: 'Packung', short: 'Pkg.' },
  { id: 'm', name: 'Meter (m)', short: 'm' },
]

export const PRODUCT_CATEGORIES_HANDEL = [
  { id: 'tee', name: 'Tee', icon: '🍵' },
  { id: 'kaffee', name: 'Kaffee', icon: '☕' },
  { id: 'gewuerze', name: 'Gewürze', icon: '🌶️' },
  { id: 'lebensmittel', name: 'Lebensmittel', icon: '🥫' },
  { id: 'kosmetik', name: 'Kosmetik', icon: '🧴' },
  { id: 'textil', name: 'Textilien', icon: '🧵' },
  { id: 'elektronik', name: 'Elektronik', icon: '🔌' },
  { id: 'handwerk', name: 'Handwerk', icon: '🛠️' },
  { id: 'sonstiges', name: 'Sonstiges', icon: '📦' },
]

export const PURCHASE_STATUSES = [
  { id: 'eingekauft', label: 'Eingekauft', color: 'bg-blue-100 text-blue-700', icon: '🛒' },
  { id: 'im_lager', label: 'Im Lager', color: 'bg-green-100 text-green-700', icon: '📦' },
  { id: 'teilweise_verkauft', label: 'Teilw. verkauft', color: 'bg-yellow-100 text-yellow-700', icon: '📊' },
  { id: 'ausverkauft', label: 'Ausverkauft', color: 'bg-gray-100 text-gray-600', icon: '✅' },
  { id: 'storniert', label: 'Storniert', color: 'bg-red-100 text-red-700', icon: '❌' },
  { id: 'reklamation', label: 'Reklamation', color: 'bg-orange-100 text-orange-700', icon: '⚠️' },
]

export const SALE_STATUSES = [
  { id: 'offen', label: 'Offen', color: 'bg-yellow-100 text-yellow-700', icon: '⏳' },
  { id: 'bezahlt', label: 'Bezahlt', color: 'bg-green-100 text-green-700', icon: '💰' },
  { id: 'geliefert', label: 'Geliefert', color: 'bg-blue-100 text-blue-700', icon: '🚚' },
  { id: 'abgeschlossen', label: 'Abgeschlossen', color: 'bg-gray-100 text-gray-600', icon: '✅' },
]

// ═══════════════════════════════════════════
// Tracker Module
// ═══════════════════════════════════════════

export const TRACKER_LABELS = {
  tracker: 'Tracker',
  trackerDashboard: 'Tracker-Übersicht',
  trackerListe: 'Meine Tracker',
  neuerTracker: 'Neuer Tracker',
  eigenerTracker: 'Eigener Tracker',
  vorlagen: 'Vorlagen',
  trackerName: 'Name',
  typ: 'Typ',
  einheit: 'Einheit',
  tagesziel: 'Tagesziel',
  zielrichtung: 'Zielrichtung',
  maximal: 'Maximal (nicht überschreiten)',
  minimal: 'Mindestens erreichen',
  kostenProEinheit: 'Kosten pro Einheit',
  monatskosten: 'Monatliche Kosten',
  untertypen: 'Untertypen',
  materialien: 'Materialien',
  materialName: 'Materialname',
  packungsmenge: 'Packungsmenge',
  packungspreis: 'Packungspreis',
  verbrauchProStück: 'Verbrauch pro Stück',
  kostenProStück: 'Kosten pro Stück',
  eintrag: 'Eintrag',
  einträge: 'Einträge',
  neuerEintrag: 'Neuer Eintrag',
  keineEinträge: 'Noch keine Einträge vorhanden',
  keineTracker: 'Noch keine Tracker angelegt',
  heute: 'Heute',
  dieseWoche: 'Diese Woche',
  dieserMonat: 'Dieser Monat',
  anzahl: 'Anzahl',
  kosten: 'Kosten',
  dauer: 'Dauer',
  minuten: 'Minuten',
  uhrzeit: 'Uhrzeit',
  fortschritt: 'Fortschritt',
  streak: 'Streak',
  tageInFolge: 'Tage in Folge',
  bestStreak: 'Bester Streak',
  trend: 'Trend',
  wochenvergleich: 'Wochenvergleich',
  durchschnitt: 'Durchschnitt',
  proTag: 'pro Tag',
  gesamt: 'Gesamt',
  ersparnis: 'Ersparnis',
  ersparnisRechner: 'Ersparnis-Rechner',
  kostenvergleich: 'Kostenvergleich',
  wenigerProTag: 'weniger pro Tag',
  proMonat: 'pro Monat',
  proJahr: 'pro Jahr',
  gespart: 'gespart',
  gekauft: 'Gekauft',
  gedreht: 'Gedreht',
  eZig: 'E-Zigarette',
  zumTracker: 'Zum Tracker',
  schnellEintrag: '+1',
}

export const TRACKER_TYPES = [
  { id: 'counter', name: 'Zähler', icon: '🔢', desc: 'Einfach zählen (z.B. Zigaretten, Gläser Wasser)' },
  { id: 'kosten', name: 'Kosten', icon: '💰', desc: 'Zählen + Kosten tracken' },
  { id: 'zeit', name: 'Zeit', icon: '⏱️', desc: 'Dauer tracken (z.B. Training, Meditation)' },
  { id: 'kombi', name: 'Kombi', icon: '📊', desc: 'Zählen + Kosten + Untertypen' },
]

export const TRACKER_PRESETS = [
  {
    id: 'zigaretten',
    name: 'Zigaretten',
    icon: '🚬',
    color: '#EF4444',
    type: 'kombi',
    unit: 'Stk.',
    daily_goal: 10,
    goal_direction: 'max',
    cost_per_unit: 0.35,
    has_subtypes: true,
    subtypes: ['gekauft', 'gedreht', 'e-zig'],
    is_smoking_tracker: true,
    defaultMaterials: [
      { name: 'Tabak (30g)', package_amount: 30, package_unit: 'g', package_price: 7.00, usage_per_cig: 0.7 },
      { name: 'Blättchen (50 Stk.)', package_amount: 50, package_unit: 'Stk.', package_price: 1.50, usage_per_cig: 1 },
      { name: 'Filter (120 Stk.)', package_amount: 120, package_unit: 'Stk.', package_price: 1.20, usage_per_cig: 1 },
    ],
  },
  {
    id: 'fitness',
    name: 'Fitness / Training',
    icon: '💪',
    color: '#3B82F6',
    type: 'zeit',
    unit: 'Min.',
    daily_goal: 30,
    goal_direction: 'min',
    has_subtypes: false,
    subtypes: [],
    is_smoking_tracker: false,
  },
  {
    id: 'haushalt',
    name: 'Haushalt',
    icon: '🧹',
    color: '#10B981',
    type: 'counter',
    unit: 'Aufg.',
    daily_goal: 3,
    goal_direction: 'min',
    has_subtypes: false,
    subtypes: [],
    is_smoking_tracker: false,
  },
  {
    id: 'sauna',
    name: 'Sauna',
    icon: '♨️',
    color: '#F59E0B',
    type: 'kombi',
    unit: 'Gänge',
    daily_goal: 0,
    goal_direction: 'max',
    cost_per_unit: 5.00,
    has_subtypes: false,
    subtypes: [],
    is_smoking_tracker: false,
  },
]

export const SMOKING_SUBTYPES = [
  { id: 'gekauft', name: 'Gekauft', icon: '🏪', color: 'bg-red-100 text-red-700' },
  { id: 'gedreht', name: 'Gedreht', icon: '🌿', color: 'bg-green-100 text-green-700' },
  { id: 'e-zig', name: 'E-Zigarette', icon: '💨', color: 'bg-blue-100 text-blue-700' },
]

export const TRACKER_ICONS = [
  '🚬', '💪', '🧹', '♨️', '🏃', '🧘', '💧', '🍎', '📖', '💊',
  '☕', '🍺', '🎯', '⏰', '🛏️', '🚶', '🏊', '🚴', '📝', '🎵',
  '🧠', '💤', '🌙', '🌞',
]

export const TRACKER_COLORS = [
  '#EF4444', '#F59E0B', '#10B981', '#3B82F6', '#8B5CF6',
  '#EC4899', '#F97316', '#14B8A6', '#6366F1', '#78716C',
]
