export const LABELS = {
  appName: 'FamInventar',
  dashboard: 'Übersicht',
  collections: 'Inventar',
  newItem: 'Neues Teil',
  newCollection: 'Neue Kategorie',
  playLog: 'Spielprotokoll',
  statistics: 'Statistik',
  settings: 'Einstellungen',
  login: 'Anmelden',
  register: 'Registrieren',
  logout: 'Abmelden',
  save: 'Speichern',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  edit: 'Bearbeiten',
  add: 'Hinzufügen',
  search: 'Suchen...',
  value: 'Wert',
  totalValue: 'Gesamtwert',
  noItems: 'Noch keine Teile vorhanden',
  noCollections: 'Noch keine Kategorien vorhanden',
  noPlayLogs: 'Noch keine Spielsitzungen erfasst',
  items: 'Teile',
  item: 'Teil',
  collection: 'Kategorie',
  name: 'Name',
  description: 'Beschreibung',
  category: 'Kategorie',
  photo: 'Foto',
  type: 'Typ',
  normal: 'Normal',
  toy: 'Spielzeug',
  topToys: 'Top 5 Lieblingsspielzeuge',
  playSession: 'Spielsitzung',
  logPlay: 'Spiel eintragen',
  duration: 'Dauer (Minuten)',
  notes: 'Notizen',
  all: 'Alle',
  email: 'E-Mail',
  password: 'Passwort',
  passwordConfirm: 'Passwort bestätigen',
  noAccount: 'Noch kein Konto?',
  hasAccount: 'Bereits ein Konto?',
  welcome: 'Willkommen!',
  next: 'Weiter',
  back: 'Zurück',
  finish: 'Fertig',
  totalItems: 'Gesamte Teile',
  totalCollections: 'Kategorien',
  playHours: 'Spielstunden',
  recentActivity: 'Letzte Aktivitäten',
  valueByCollection: 'Wert pro Kategorie',
  playFrequency: 'Spielhäufigkeit',
  categoryDistribution: 'Kategorieverteilung',
  valueTab: 'Wert',
  playTab: 'Spielen',
  collectionsTab: 'Kategorien',
  confirmDelete: 'Wirklich löschen?',
  confirmDeleteText: 'Diese Aktion kann nicht rückgängig gemacht werden.',
  owner: 'Besitzer',
  createdAt: 'Erstellt am',
  lastPlayed: 'Zuletzt gespielt',
  playCount: 'Gespielt',
  times: 'Mal',
  euro: '€',
  uploadPhoto: 'Foto hochladen',
  changePhoto: 'Foto ändern',
  removePhoto: 'Foto entfernen',
  loading: 'Laden...',
  error: 'Fehler',
  success: 'Erfolgreich',
  // Extended item fields
  location: 'Standort',
  borrowedTo: 'Ausgeborgt an',
  acquiredType: 'Herkunft',
  bought: 'Gekauft',
  gifted: 'Geschenkt',
  store: 'Geschäft / Laden',
  giftedFrom: 'Geschenkt von',
  occasion: 'Anlass',
  acquiredDate: 'Kaufdatum',
  receipt: 'Rechnung',
  uploadReceipt: 'Rechnung hochladen',
  viewReceipt: 'Rechnung ansehen',
  imageUrl: 'Bild-URL',
  orUrl: 'oder URL einfügen',
  moreDetails: 'Weitere Details',
  hideDetails: 'Details ausblenden',
  noOccasion: 'Kein bestimmter Anlass',
  acquiredInfo: 'Herkunft & Kauf',
  photoUrlPlaceholder: 'Bild-URL einfügen...',
  saveUrl: 'URL speichern',
}

export const CATEGORIES = [
  // Kleidung & Accessoires
  { id: 'schuhe', name: 'Schuhe', icon: '👟' },
  { id: 'jacken', name: 'Jacken & Mäntel', icon: '🧥' },
  { id: 'kleidung', name: 'Kleidung', icon: '👗' },
  { id: 'schmuck', name: 'Schmuck & Uhren', icon: '💍' },
  { id: 'taschen', name: 'Taschen & Koffer', icon: '👜' },

  // Elektronik & Medien
  { id: 'elektronik', name: 'Elektronik', icon: '📱' },
  { id: 'konsolen', name: 'Spielkonsolen', icon: '🎮' },
  { id: 'ps5', name: 'PS5 Spiele', icon: '🕹️' },
  { id: 'ps4', name: 'PS4 Spiele', icon: '🎮' },
  { id: 'xbox', name: 'Xbox Spiele', icon: '🟢' },
  { id: 'nintendo', name: 'Nintendo Spiele', icon: '🔴' },
  { id: 'pc_spiele', name: 'PC Spiele', icon: '🖥️' },
  { id: 'videospiele', name: 'Videospiele (allg.)', icon: '👾' },
  { id: 'cd', name: 'CDs', icon: '💿' },
  { id: 'dvd', name: 'DVDs & Blu-ray', icon: '📀' },
  { id: 'vinyl', name: 'Vinyl / Schallplatten', icon: '🎶' },

  // Spielzeug & Kinder
  { id: 'puppen', name: 'Puppen & Stofftiere', icon: '🧸' },
  { id: 'lego', name: 'LEGO & Bausteine', icon: '🧱' },
  { id: 'puzzle', name: 'Puzzle', icon: '🧩' },
  { id: 'brettspiele', name: 'Brettspiele', icon: '🎲' },
  { id: 'autos', name: 'Spielzeugautos', icon: '🚗' },
  { id: 'figuren', name: 'Figuren & Actionfiguren', icon: '🦸' },

  // Sammlungen & Hobby
  { id: 'muenzen', name: 'Münzen', icon: '🪙' },
  { id: 'karten', name: 'Sammelkarten', icon: '🃏' },
  { id: 'briefmarken', name: 'Briefmarken', icon: '📮' },
  { id: 'comics', name: 'Comics & Manga', icon: '📖' },
  { id: 'buecher', name: 'Bücher', icon: '📚' },
  { id: 'kunst', name: 'Kunst & Deko', icon: '🎨' },
  { id: 'musik_instr', name: 'Musikinstrumente', icon: '🎸' },

  // Haus & Garten
  { id: 'moebel', name: 'Möbel', icon: '🛋️' },
  { id: 'kueche', name: 'Küche & Haushalt', icon: '🍳' },
  { id: 'werkzeug', name: 'Werkzeug', icon: '🔧' },
  { id: 'garten', name: 'Garten', icon: '🌿' },

  // Sport & Outdoor
  { id: 'sport', name: 'Sport & Fitness', icon: '⚽' },
  { id: 'outdoor', name: 'Outdoor & Camping', icon: '🏕️' },
  { id: 'fahrrad', name: 'Fahrrad & Zubehör', icon: '🚲' },

  // Fahrzeuge
  { id: 'auto', name: 'Auto & Zubehör', icon: '🚙' },

  // Sonstiges
  { id: 'sonstiges', name: 'Sonstiges', icon: '📦' },
]

export const LOCATIONS = [
  { id: 'zuhause', name: 'Zuhause', icon: '🏠' },
  { id: 'keller', name: 'Keller', icon: '📦' },
  { id: 'dachboden', name: 'Dachboden', icon: '🏚️' },
  { id: 'garage', name: 'Garage', icon: '🚗' },
  { id: 'buero', name: 'Büro / Arbeit', icon: '🏢' },
  { id: 'lager', name: 'Lagerraum', icon: '🏗️' },
  { id: 'ausgeborgt', name: 'Ausgeborgt', icon: '🔄' },
]

export const OCCASIONS = [
  { id: 'geburtstag', name: 'Geburtstag', icon: '🎂' },
  { id: 'weihnachten', name: 'Weihnachten', icon: '🎄' },
  { id: 'ramadan', name: 'Ramadan', icon: '🌙' },
  { id: 'eid', name: 'Eid', icon: '🕌' },
  { id: 'ostern', name: 'Ostern', icon: '🐰' },
  { id: 'hochzeit', name: 'Hochzeit', icon: '💒' },
  { id: 'einschulung', name: 'Einschulung', icon: '🎒' },
  { id: 'namenstag', name: 'Namenstag', icon: '📛' },
  { id: 'sonstiges', name: 'Sonstiger Anlass', icon: '🎁' },
]

export const COLLECTION_ICONS = [
  '👟', '🧥', '👗', '💍', '👜', '📱', '🎮', '🕹️', '👾', '💿',
  '📀', '🎶', '🧸', '🧱', '🧩', '🎲', '🚗', '🦸', '🪙', '🃏',
  '📮', '📖', '📚', '🎨', '🎸', '🛋️', '🍳', '🔧', '🌿', '⚽',
  '🏕️', '🚲', '🚙', '📦', '🎁', '💎', '🏆', '🎯', '💡', '🧪',
]

export const AVATARS = [
  '👦', '👧', '👨', '👩', '🧒', '👶',
  '🦊', '🐻', '🐰', '🐱', '🐶', '🦄',
  '🌟', '🌈', '🦋', '🌸', '⚡', '🎈',
]

export const CHART_COLORS = [
  '#FF8A65', '#4DB6AC', '#FFD54F', '#CE93D8', '#81D4FA',
  '#A5D6A7', '#F48FB1', '#FFAB91', '#80CBC4', '#FFF176',
]
